version: '3.8'
services:
  web:
    build: .
    command: sh -c "uvicorn blog_fast_api_python.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    container_name: blog_fast_api_python

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
